name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.11"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update apt
      run: |
        sudo apt-get update
    - name: Install RabbitMQ
      run: |
        sudo apt-get install -y rabbitmq-server
    - name: Run test
      uses: fizyk/actions-reuse/.github/actions/pipenv@v4.4.4
      with:
        python-version: ${{ matrix.python-version }}
        command: python -m coverage run -m pytest -p no:xdist
        allow-prereleases: true
        env: '{"COVERAGE_PROCESS_START": ".coveragerc", "COVERAGE_FILE": ".coverage.serial"}'
    - name: Combine and export serial coverage
      if: always()
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.4
      env:
        COVERAGE_FILE: .coverage.serial
      with:
        command: python -m coverage combine || true && python -m coverage xml -o coverage-serial.xml || true
    - name: Run xdist test
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.4
      with:
        command: python -m coverage run -m pytest -n auto --max-worker-restart=0
        env: '{"COVERAGE_PROCESS_START": ".coveragerc", "COVERAGE_FILE": ".coverage.xdist"}'
    - name: Combine and export xdist coverage
      if: always()
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.4
      env:
        COVERAGE_FILE: .coverage.xdist
      with:
        command: python -m coverage combine || true && python -m coverage xml -o coverage-xdist.xml || true
    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v5.5.2
      with:
        files: coverage-serial.xml,coverage-xdist.xml
        flags: linux
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
