name: Run tests with oldest supported dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-oldest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.11"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update apt
      run: |
        sudo apt-get update
    - name: Install RabbitMQ
      run: |
        sudo apt-get install -y rabbitmq-server
    - name: Setup python
      uses: fizyk/actions-reuse/.github/actions/pipenv-setup@v4.4.5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install oldest dependencies
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.5
      with:
        command: pip install -r oldest/requirements.txt
    - name: Run test
      id: run_serial_tests
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.5
      with:
        command: python -m coverage run -m pytest -c pyproject.oldest.toml -p no:xdist
        env: '{"COVERAGE_PROCESS_START": ".coveragerc", "COVERAGE_FILE": ".coverage.serial"}'
    - name: Combine and export serial coverage
      if: ${{ always() && (steps.run_serial_tests.conclusion == 'success' || steps.run_serial_tests.conclusion == 'failure') }}
      uses: fizyk/actions-reuse/.github/actions/coverage-combine-export@v4.4.5
      with:
        data-file: .coverage.serial
        output-file: coverage-serial.xml
    - name: Run xdist test
      id: run_xdist_tests
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.5
      with:
        command: python -m coverage run -m pytest -c pyproject.oldest.toml -n auto --max-worker-restart=0
        env: '{"COVERAGE_PROCESS_START": ".coveragerc", "COVERAGE_FILE": ".coverage.xdist"}'
    - name: Combine and export xdist coverage
      if: ${{ always() && (steps.run_xdist_tests.conclusion == 'success' || steps.run_xdist_tests.conclusion == 'failure') }}
      uses: fizyk/actions-reuse/.github/actions/coverage-combine-export@v4.4.5
      with:
        data-file: .coverage.xdist
        output-file: coverage-xdist.xml
    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v5.5.2
      with:
        files: coverage-serial.xml,coverage-xdist.xml
        flags: linux
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
